# Generated by Django 3.0.5 on 2020-04-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20200425_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(max_length=128, verbose_name='사용자이메일'),
        ),
    ]
